version: '{build}'
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
    - master
skip_tags: true
image: Visual Studio 2019
configuration:
  - Debug
  - Release
shallow_clone: true
artifacts:
  - path: src/Tgstation.Server.ControlPanel.Windows/Releases/Setup.exe
    name: SetupExe
  - path: src/Tgstation.Server.ControlPanel.Windows/Releases/Setup.msi
    name: SetupMsi
  - path: src/Tgstation.Server.ControlPanel.Windows/Releases/RELEASES
    name: ReleaseMetadata
  - path: src/Tgstation.Server.ControlPanel.Windows/Releases/Tgstation.Server.ControlPanel.Windows-*full.nupkg
    name: ReleasePackage
cache:
  - ~\.nuget\packages -> **\*.csproj
install:
#  - nuget sources add -Name AvaloniaNightlies -Source https://www.myget.org/F/avalonia-ci/api/v2
  - nuget restore Tgstation.Server.ControlPanel.sln
build:
  project: Tgstation.Server.ControlPanel.sln
  parallel: false
  verbosity: minimal
after_test:
  - ps: $env:TGCPVersion = [System.Diagnostics.FileVersionInfo]::GetVersionInfo("$env:APPVEYOR_BUILD_FOLDER/src/Tgstation.Server.ControlPanel/bin/$env:CONFIGURATION/net6.0/Tgstation.Server.ControlPanel.dll").FileVersion
  - ps: if($env:APPVEYOR_REPO_COMMIT_MESSAGE -match "\[TGSDeploy\]"){ if($env:APPVEYOR_REPO_BRANCH -match "master"){ if($env:CONFIGURATION -match "Release"){ $env:TGSDeploy = "Do it." }}}
deploy:
  - provider: GitHub
    release: "Tgstation.Server.ControlPanel-v$(TGCPVersion)"
    description: 'The /tg/station server suite'
    auth_token:
      secure: lJNGAXwiB5HlWdthz3K4PetqpTG5IEAyRgKaiKxFMQ8HW8CcOjRtB97B05op7BsK
    artifact: SetupExe,SetupMsi,ReleaseMetadata,ReleasePackage
    draft: true
    on:
      TGSDeploy: "Do it."
